export const siteConfig = {
  name: "Paola Thomson - Software Engineer",
  authorName: "Paola Thomson",
  username: "paolaThomson",
  description: "Paola Thomson - Software Engineer",
  url: "https://paolathomson.com",
  keywords: [
    "Paola Thomson",
    "Software Engineer",
    "Full Stack Developer",
    "Machine Learning",
    "Data Engineering",
    "UBS",
    "Python Developer",
    "React Developer",
    "Next.js Developer",
    "TypeScript",
    "Databricks",
    "AI Startups",
    "Software Development",
    "Web Developer",
    "Backend Developer",
    "Frontend Developer",
    "Tech Portfolio",
  ],
  ogImage: "/ogImage.png",
  iconIco: "/experience/coding_logo3.png",
  logoIcon: "/experience/coding_logo3.png",
  links: {
    twitter: "",
    github: "",
    templateRepo: "",
  },
};
